### ISSUE TITLE
How to properly evaluate 

### ISSUE THREAD

**Issue by Aneeshers** [taznux/lung-image-analysis#12]
Hey @taznux,
I'm very excited that the code has now finally functioned properly! So now after running the program, I was wondering how you evaluate the result.... For example like where to find the coordinates of the nodules detected per CT slice or like an image of the nodule etc... Or like a key to how to read the results? 
Thank you for your hard work, Aneesh
Happy 2017!

**Comment by taznux** [comment]
Hi Aneesh,

I recommend reading these papers which have how to evaluate nodule detection systems.

https://www.researchgate.net/publication/257947124_Genetic_programming-based_feature_transform_and_classification_for_the_automatic_detection_of_pulmonary_nodules_on_computed_tomography_images

https://arxiv.org/abs/1612.08012

If you want to see the image in MATLAB, this code is very useful. https://www.mathworks.com/matlabcentral/fileexchange/47463-imshow3dfull--3d-imshow-in-3-views-

Each mat file can be loaded in MATLAB, and you can see what are in the file. There are CT image, its lung mask, detected nodules in the volume, a table for the ground truth nodules, and another table for detected nodules.

Thanks,
Wookjin
