### ISSUE TITLE
FP reduction code is not in main.m

### ISSUE THREAD

**Issue by yexing99** [taznux/lung-image-analysis#13]
Hi, 

I'm trying to use this framework to detect nodule but found the FP reduction code is not in main.m. Once I run this code, for each patient, I got more than 900 nodules. It will be great if you can share with me how to do FP reduction to achieve the same result as your paper.

Thanks

**Comment by taznux** [comment]
Hi,

Actually, this code was re-implemented after I left the lab where I published several lung nodule detection papers. So I don't have the full set of the code in my paper. Sorry about it.

Thanks,
Wookjin

**Comment by yexing99** [comment]
Thanks Wookjin for the information. Is it possible for me to have the contact names from your previous lab who is now having control of your code or the updated version of the code?

**Comment by taznux** [comment]
I'm not sure they have the code. This guy (http://sipl.gist.ac.kr/people/intro/Yoon%20Ji%20Seok/ji%20seok.html) re-implemented it and used to study this topic. However, he changed his topic recently.

**Comment by yexing99** [comment]
Thanks so much,
Ye
