### ISSUE TITLE
Project Deign Confusion +.sid issue

### ISSUE THREAD

**Issue by Aneeshers** [taznux/lung-image-analysis#9]
HI again,
So I was running this project, first I get an error at line 207 in main.m
```
I get the error
error: matrix cannot be indexed with .
error: called from
    main at line 207 column 1
error: evaluating argument list element number 1
error: called from
    main at line 207 column 1
```
So then  I change 
`for sid = unique(nodule_detection_evaluation.sid)'
`
to 
`for sid = unique(nodule_detection_evaluation)'
`
Then this is where I'm having trouble understanding the design of the project.
So when I input about 133 LIDC_IDRC images (DICOM) like this

```
path_nodule = [pwd '/output_data']; %pwd : returns the current directory
path_data = [pwd '/Users/aneeshers/Documents/LIDC-DRI/DICOM']; %dcm files directory

```
This than results to 
`nodule_detection_summary = [](0x0)
`
Which doesn't sound right. So after experimenting different paths and what not, I decided to see what happens when no path is given like so
`path_data = [pwd '']; %dcm files directory
`
Which also gave me the same result!
So then I concluded that it was not the right place to out the path, I tried it in the output path because of the name path_nodule. But that also did not work out well. So then I start retracing the input which looks like it is 
`    filename_input = [ct_img_path pid '_input.mat'];
`
What I don't understand is what the `pids` is and what it is for? I opened it in the output file generated, which just shows 
```
# Created by Octave 4.0.3, Thu Dec 29 22:48:06 2016 EST <aneeshers@Aneeshs-MacBook-Pro.local>
# name: dicom_path_list
# type: cell
# rows: 0
# columns: 0


# name: pid_list
# type: cell
# rows: 0
# columns: 0

```
So yea that's so far that's been in my mind, then I tested the dicom read function by immediately assigning 
`ipath = '/Users/aneeshers/Documents/LIDC-DRI/DICOM' `
I'm still testing this part......
_## So what would be the appropriate way to input the data? Is it possible to show me an example of your dicom_pid_list.mat?_

Thank you so much for your time and effort, Aneeshers

**Comment by taznux** [comment]
Same answer on #8.
